version: '3.8'

services:
  company-service:
    image: company-service
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:5193"
      SqlServerConfiguration__ConnectionString: "Server=mssql;Database=CompanyDb;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True"
      Serilog__WriteTo__1__Args__serverUrl: "http://seq:80"
    ports:
      - "5193:5193"
    depends_on:
      - mssql
      - seq
    restart: always

  mssql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: mssql
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    restart: always
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "YourStrong!Passw0rd", "-Q", "SELECT 1"]
      interval: 10s
      retries: 5
      
  seq:
    image: datalust/seq
    container_name: seq
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
      - SEQ_ENABLEAUTHENTICATION=false
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:5193/api
    depends_on:
      - company-service
    restart: always