name: Run Unit Tests

on:
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore CompanyService.sln

      - name: Build solution
        run: dotnet build CompanyService.sln --configuration Release --no-restore

      - name: Run unit tests
        run: dotnet test CompanyService.Tests/CompanyService.Tests.csproj --configuration Release --no-build --verbosity normal --filter FullyQualifiedName~UnitTests