name: Run Unit Tests

on:
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    name: Run Backend Unit Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore CompanyService.sln
        
      - name: Run backend unit tests
        run: dotnet test CompanyService.Tests/CompanyService.Tests.csproj --configuration Release --verbosity normal --filter FullyQualifiedName~UnitTests
